### ISSUE TITLE
[enhancement] Format of authors and keywords file

### ISSUE THREAD

**Issue by Simske** [matiscke/scan_astro-ph#8]
Currently the rankings of authors and keywords is JSON inside the `authors.txt` and `keywords.txt` files.
In my opinion this is a bit confusing, because:
- mismatch between file suffix and syntax
- multiple files even though JSON would support both in the same file

My suggestion would be to either use YAML or INI for a single configuration file, which then could also contain other options (such as minimum rating, etc). Both are equally easy to parse in Python.
Example configurations:
YAML:
```yaml
authors:
  Alpher: 1
  Bethe: 2
  Gamov: 3

keywords:
  star: 1
  planet: 2
  habitable: 3

options;
  minimum_rating: 6
```
INI format
```ini
[authors]
Alpher = 1
Bethe = 2
Gamov = 3

[keywords]
star = 1
planet = 2
habitable = 3

[options]
minimum_rating = 6
```

I would prefer the INI format, just because it's easier to handle for the user, YAML is very powerful, but overkill for this application (and very picky about whitespace, which can be a problem for some users).

If #5 gets merged it is maybe also worth thinking about a default configuration location, such that the user can run the program anywhere without worrying about the location of the config file.
